version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Flake8
          command: |
            sudo pip3 install flake8
            flake8 .
      - run:
          name: Tests
          command: ./test.sh

workflows:
  version: 2
  feature_branch:
    jobs:
      - test
